default_context:
  project_name: 'Passmate'
  project_slug: 'passmate'
  domain_main: 'passmate.us'
  domain_staging: 'stag.passmate.us'
  docker_swarm_stack_name_main: 'passmate-us'
  docker_swarm_stack_name_staging: 'stag-passmate-us'
  secret_key: '360cec6f787f99ad3821fd165b25b29084f7b84a6bda44e7393b272173095610'
  first_superuser: 'admin@passmate.us'
  first_superuser_password: 'go4Passmate'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.passmate.us", "https://stag.passmate.us", "https://passmate.us", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '465'
  smtp_host: 'smtp.zoho.com'
  smtp_user: 'chandler@passmate.us'
  smtp_password: 'A1a7IIwrF649'
  smtp_emails_from_email: 'chandler@passmate.us'
  postgres_password: 'go4Passmate'
  pgadmin_default_user: 'admin@passmate.us'
  pgadmin_default_user_password: 'go4Passmate'
  traefik_constraint_tag: 'passmate.us'
  traefik_constraint_tag_staging: 'stag.passmate.us'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:go4Passmate'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
