"""Add columns first_name, last_name, zip_code, phone_number to User model

Revision ID: 0713bc077297
Revises: 563364ef5d7c
Create Date: 2021-05-17 22:57:26.073414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0713bc077297'
down_revision = '563364ef5d7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.drop_column('user', 'last_name')
    # ### end Alembic commands ###
