"""Add columns first_name, last_name, zip_code, phone_number to User model

Revision ID: 563364ef5d7c
Revises: a8166ba5f504
Create Date: 2021-05-17 22:52:32.479458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '563364ef5d7c'
down_revision = 'a8166ba5f504'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
