"""Rating System tables added

Revision ID: 792c5f21dfe8
Revises: 48872b8033a3
Create Date: 2021-09-03 01:28:14.149220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '792c5f21dfe8'
down_revision = '48872b8033a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events_event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rating_event_id'), 'rating', ['event_id'], unique=False)
    op.create_index(op.f('ix_rating_id'), 'rating', ['id'], unique=False)
    op.create_index(op.f('ix_rating_user_id'), 'rating', ['user_id'], unique=False)
    op.add_column('events_event', sa.Column('rating_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_events_event_rating_id'), 'events_event', ['rating_id'], unique=False)
    op.create_foreign_key(None, 'events_event', 'rating', ['rating_id'], ['id'])
    op.alter_column('user', 'zip_code',
               existing_type=sa.BIGINT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'zip_code',
               existing_type=sa.String(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.drop_constraint(None, 'events_event', type_='foreignkey')
    op.drop_index(op.f('ix_events_event_rating_id'), table_name='events_event')
    op.drop_column('events_event', 'rating_id')
    op.drop_index(op.f('ix_rating_user_id'), table_name='rating')
    op.drop_index(op.f('ix_rating_id'), table_name='rating')
    op.drop_index(op.f('ix_rating_event_id'), table_name='rating')
    op.drop_table('rating')
    # ### end Alembic commands ###
